@@include('index/index.js')
@@include('card/card.js')
@@include('category/category.js')
@@include('catalog/catalog.js')
@@include('detail/detail.js')
@@include('pay/pay.js')
@@include('search/search.js')